language: node_js
sudo: required
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install: true
before_script:
- export DOCKER_HOST="$HOST_NAME"
script:
- docker build -t $DOCKER_USERNAME/htmltest
- docker push $DOCKER_USERNAME/htmltest
after_success:
- docker stop htmltest
- docker rm htmltest
- docker run -p 8088:80 -d  --name htmltest 592115518/lab9:latest
service: docker
env:
  global:
  - secure: IsOzIk3OQBnntPZ6QyQhrcaNMZ138dV9Ozn5ReHOMCThIo0/r4vs2Abjh5gAbbcrJgFM+M/Yt4wsZMW2ZWNH7Uh1n+sgpfAVarMCAtDUh8BSYmRtlpnXzkzKnka+ysN53BIufgS4g3opjhPF3NmARAh6maI1SNsRsp8i1DO28pb9Hin9mPvIgmem1O4Jde3XqAntISluzMo+8KpBI/Gmo2EPFKMQ5qh0LWqpeAZiikukGK3WvsRyhot7I7fLGRTv41qg2zqM0t2EKOhJtFIXGKUjX2kVeDQD8iEIje7m0c79YnWGm4Ty+NqWhQyf51HIg4r+Yvyg7cbIjfrFf/uwXJrYO1j+UmeToLNcqEwaBXWaHVwr75Th11rWpUQpMXmrXiNM4DX2Dm9K/VZV8afbqn3QbOI/EmgmtcOm3g/KeIyry7Er6fQuA05tPseN/uMdOxGZl3Oq5rLeDAiArsUs93cJq3K3wAMyUEKoGdLjHHCQDbbKF0D+RG7U4pIpx2OYyAQCHSmLywGLC/lWb4CWcjC3FaFzedOxQ7Djtg7i/5nOT2/F5i/fBH+FWz7EJ90fwfGkkka1xJ3OsRLKtLhE74EPZ9XknwjfIzUEcg+IbbJhgdfhVKYhbhdnnWsj6KmTXH+9KsVSdaMbo/+iWhCThnsaBoquSzSsPWhyNN2K2ok=
  - secure: idh8+RS2oXDYdcV9q42/q06pzPdhuogCAsT2CZ5HbdfFaV0EW2yIVACMepNMhrfwHwsrK/rFfEUCc2aimNPoOPXfr5qSHte6qrw3IHKGK7qeuuptA6APLLh1hbYsZ3N6a3dwcZ9fMQgfNv3hl8IYo2xswaMxVFdSb0vXTTbfrvBh22cqkYTdjKcQrdWejlqAFpCNoj3Ll4uywKlZZt2tTJpFzHVe6hNabzRT3nXJ0Y8YiOi8hy1yb8zNOi8sjG3dWioGsIYGmXbBd8Op4m3BDQCkWcm48PPYsNIL7hGK4l1/zE+Fklgl+fsiqh14GiSghDNxOF2xRkBc2ySkq2CcWEJM0XVeIG0HxsoZzxDrVTtFfTUux2RD5IhQdSLcWrGZHmImvdWM9znZ4f45J3gW86CS3aKomMJF4VPT2Y8kFazu/+kH1zPb+wE6YMg5/CbcoBvfyjPYwrkfKMgN83OPmIxTi/slTEOzYOfbm+hXvddyAyPWZBoExUwp1IGr9ZWZ1ZfoZfelmgUjF2b2VFvyFqU26/DddXQh7F6FiTuOJf/cER0Rips58BsxQ9MdaxeAfZclWiJclFHRNvCA9wcs61ry+AniuCf+rVMZFTYtOUi+MUTBSeVc75+TB/7EY8AHOqX6tHo5AtfVQ4NAFo1i5XXlYuKi7MshfRO9ErQt1P4=
  - secure: fMmHPOavUqqnEeOSNL+deot968hRFFbDNfTmSTRHWmxAcgHZGlZMlc7KXn3vADdBuTaOe2s1JbYOLrfHegcMZS3Bw69JQ+Emqf4JIjQ+UDlvGq8ECiI8GXYbjqlRsPkAE6sIy821dYkLbuXBzWkl7Ain3TYYVlqdLgssbOJFH5gNjcoghDKNZ5SokjS+P2UyUT37CnYILBrGJBmNalM+sa/z03Q3BrQmmXo6NYSYRwXjtEOgiuOtmL5dLr71MfbIOlerZNXRTGclyLWZClgfyPt5A0s5cRESMsFo7LZ5Kl4v9tK+fcDnNaJYdBRiKgBVkwu8L7tqN8evxLaOaieONP1XpvFtQuOfT3wNWnv//rYQIoNqm5zpS7vX4/9sjmx1Ae5eF6wYciUzkTD/KAzd+C8j+B/vZ7nOfLldvyRM6tEY5BxPkvrFogoO12zE3bWmdyOT5UawZWhvsf/GeiV7aZ786y+bOw1x8V76K+Yh7EKNDA7We0JMG1YL/6eGRjb9qURpIpJIMO7EGNfVuYQuoXWXbufh0lrmljQ9nPqYrHMbFqtQ7epQzkOejOz6ymrc2rcWim8BVTtkrcLKL0oN/BxlLUex5B8ACTOYNZyXvUJl67GzhQqhyQUCSFZEYfHcN6HrLKiClrnpG8dS0v/T4oIa4dGg0qPO1qAsApEey+c=
